use_frameworks!

platform :ios, '9.0'

target 'RJXFoundation-ObjC_Example' do
  pod 'RJXFoundation-ObjC', :path => '../'

  target 'RJXFoundation-ObjC_Tests' do
    inherit! :search_paths

    
  end
end
